// <auto-generated />
using System;
using DreamTeam.Wod.EmployeeService.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DreamTeam.Wod.EmployeeService.Repositories.Migrations
{
    [DbContext(typeof(EmployeeServiceDbContext))]
    [Migration("20220722084525_FixCompletedAndCancelledPlanStatus")]
    partial class FixCompletedAndCancelledPlanStatus
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.CompensationInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount");

                    b.Property<string>("Currency");

                    b.Property<int>("RelocationPlanId");

                    b.HasKey("Id");

                    b.HasIndex("RelocationPlanId")
                        .IsUnique();

                    b.ToTable("CompensationInfo");
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.CurrentLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CountryId")
                        .HasMaxLength(64);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64);

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("ExternalId")
                        .IsRequired();

                    b.Property<bool>("HasCompanyOffice");

                    b.Property<bool>("IsCustom");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("IsCustom");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CurrentLocation");
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CountryId")
                        .HasMaxLength(64);

                    b.Property<int?>("CurrentLocationId");

                    b.Property<DateTime?>("DismissalDate");

                    b.Property<string>("DismissalReason");

                    b.Property<string>("DomainName")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<DateTime?>("EmploymentDate");

                    b.Property<string>("ExternalId")
                        .IsRequired();

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsContractor");

                    b.Property<string>("Location");

                    b.Property<DateTime?>("NextPrDate");

                    b.Property<string>("OrganizationId")
                        .IsConcurrencyToken()
                        .HasMaxLength(64);

                    b.Property<string>("PersonId")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<int?>("ResponsibleHrManagerId");

                    b.Property<int?>("SeniorityId");

                    b.Property<int?>("TitleRoleId");

                    b.Property<string>("UnitId")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<DateTime?>("UpdateDate");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.HasIndex("CurrentLocationId");

                    b.HasIndex("DismissalReason");

                    b.HasIndex("DomainName")
                        .IsUnique();

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.HasIndex("ResponsibleHrManagerId");

                    b.HasIndex("SeniorityId");

                    b.HasIndex("TitleRoleId");

                    b.HasIndex("IsActive", "UnitId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.EmployeeCurrentLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ChangeDate");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<int>("EmployeeId");

                    b.Property<int>("LocationId");

                    b.Property<DateTime>("SinceDate");

                    b.Property<DateTime?>("UntilDate");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.HasIndex("LocationId");

                    b.ToTable("EmployeeCurrentLocation");
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.EmployeeCurrentLocationChange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EmployeeId");

                    b.Property<int?>("NewLocationId");

                    b.Property<int?>("PreviousLocationId");

                    b.Property<DateTime>("UpdateDate");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("NewLocationId");

                    b.HasIndex("PreviousLocationId");

                    b.ToTable("EmployeeCurrentLocationChange");
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.EmployeeOrganizationChange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EmployeeId");

                    b.Property<string>("NewOrganizationId")
                        .HasMaxLength(64);

                    b.Property<string>("PreviousOrganizationId")
                        .HasMaxLength(64);

                    b.Property<DateTime>("UpdateDate");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeOrganizationChange");
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.EmployeePreferredDeliveryCenter", b =>
                {
                    b.Property<int>("PreferredDeliveryCenterId");

                    b.Property<int>("EmployeeId");

                    b.HasKey("PreferredDeliveryCenterId", "EmployeeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeePreferredDeliveryCenter");
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.EmployeePreferredDeliveryCenters", b =>
                {
                    b.Property<int>("EmployeeId");

                    b.Property<DateTime?>("ChangeDate");

                    b.Property<string>("ChangedBy")
                        .HasMaxLength(64);

                    b.Property<string>("Comment")
                        .HasMaxLength(5000);

                    b.HasKey("EmployeeId");

                    b.ToTable("EmployeePreferredDeliveryCenters");
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.EmployeeRole", b =>
                {
                    b.Property<int>("EmployeeId");

                    b.Property<int>("RoleId");

                    b.HasKey("EmployeeId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("EmployeeRole");
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.EmployeeSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CountryId")
                        .HasMaxLength(64);

                    b.Property<DateTime>("Date");

                    b.Property<int>("EmployeeId");

                    b.Property<bool>("IsActive");

                    b.Property<string>("OrganizationId")
                        .HasMaxLength(64);

                    b.Property<int?>("TitleRoleId");

                    b.Property<string>("UnitId")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("TitleRoleId");

                    b.ToTable("EmployeeSnapshot");
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.Internship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CloseReason");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("DomainName")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Email")
                        .HasMaxLength(254);

                    b.Property<DateTime>("EndDate");

                    b.Property<string>("ExternalId")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("FirstNameLocal")
                        .HasMaxLength(200);

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsDomainNameVerified");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("LastNameLocal")
                        .HasMaxLength(200);

                    b.Property<string>("Location")
                        .HasMaxLength(100);

                    b.Property<string>("PersonId")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<string>("Phone")
                        .HasMaxLength(64);

                    b.Property<string>("PhotoId")
                        .HasMaxLength(64);

                    b.Property<string>("Skype")
                        .HasMaxLength(256);

                    b.Property<DateTime>("StartDate");

                    b.Property<string>("StudentLabId")
                        .HasMaxLength(64);

                    b.Property<string>("StudentLabProfileUrl");

                    b.Property<string>("Telegram")
                        .HasMaxLength(32);

                    b.Property<string>("UnitId")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<DateTime?>("UpdateDate");

                    b.Property<string>("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("CloseReason");

                    b.HasIndex("DomainName")
                        .IsUnique()
                        .HasFilter("IsActive = 1");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("Internship");
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.PreferredDeliveryCenter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ExternalId")
                        .IsRequired();

                    b.Property<bool>("IsActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("OrganizationId")
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PreferredDeliveryCenter");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExternalId = "central_asia_kazakhstan_uzbekistan_kyrgyzstan",
                            IsActive = true,
                            Name = "Central Asia (Kazakhstan, Uzbekistan, Kyrgyzstan)"
                        },
                        new
                        {
                            Id = 2,
                            ExternalId = "georgia",
                            IsActive = true,
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = 3,
                            ExternalId = "poland",
                            IsActive = true,
                            Name = "Poland"
                        },
                        new
                        {
                            Id = 4,
                            ExternalId = "lithuania",
                            IsActive = true,
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = 5,
                            ExternalId = "czech_republic_slovakia_hungary",
                            IsActive = true,
                            Name = "Czech Republic, Slovakia, Hungary"
                        },
                        new
                        {
                            Id = 6,
                            ExternalId = "bulgaria_serbia",
                            IsActive = true,
                            Name = "Bulgaria, Serbia"
                        },
                        new
                        {
                            Id = 7,
                            ExternalId = "latam",
                            IsActive = true,
                            Name = "LATAM"
                        },
                        new
                        {
                            Id = 8,
                            ExternalId = "belarus",
                            IsActive = false,
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = 9,
                            ExternalId = "ukraine",
                            IsActive = false,
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = 10,
                            ExternalId = "uk",
                            IsActive = false,
                            Name = "UK"
                        },
                        new
                        {
                            Id = 11,
                            ExternalId = "us",
                            IsActive = false,
                            Name = "US"
                        },
                        new
                        {
                            Id = 12,
                            ExternalId = "austria",
                            IsActive = false,
                            Name = "Austria"
                        });
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.RelocationApprover", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CountryId")
                        .IsRequired();

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64);

                    b.Property<DateTime>("CreationDate");

                    b.Property<int>("EmployeeId");

                    b.Property<bool>("IsPrimary");

                    b.Property<DateTime?>("UpdateDate");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.HasIndex("CountryId")
                        .IsUnique()
                        .HasFilter("[IsPrimary] = 1");

                    b.HasIndex("EmployeeId", "CountryId")
                        .IsUnique();

                    b.ToTable("RelocationApprover");
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.RelocationCaseProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsAccommodationBooked");

                    b.Property<bool>("IsTransferBooked");

                    b.Property<bool>("IsVisaGathered");

                    b.Property<int>("RelocationPlanId");

                    b.HasKey("Id");

                    b.HasIndex("RelocationPlanId")
                        .IsUnique();

                    b.ToTable("RelocationCaseProgress");
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.RelocationCaseStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("ExternalId")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("SourceId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("SourceId")
                        .IsUnique();

                    b.ToTable("RelocationCaseStatus");
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.RelocationCaseVisaProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AreDocsGathered");

                    b.Property<bool>("AreDocsSentToAgency");

                    b.Property<bool>("IsAttended");

                    b.Property<bool>("IsPassportCollected");

                    b.Property<bool>("IsScheduled");

                    b.Property<int>("RelocationCaseProgressId");

                    b.HasKey("Id");

                    b.HasIndex("RelocationCaseProgressId")
                        .IsUnique();

                    b.ToTable("RelocationCaseVisaProgress");
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.RelocationPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("ApprovalDate");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(64);

                    b.Property<string>("ApproverComment")
                        .HasMaxLength(5000);

                    b.Property<DateTime?>("ApproverCommentChangeDate");

                    b.Property<DateTime?>("ApproverDate");

                    b.Property<int?>("ApproverId");

                    b.Property<string>("CloseComment")
                        .HasMaxLength(5000);

                    b.Property<DateTime?>("CloseDate");

                    b.Property<string>("ClosedBy")
                        .HasMaxLength(64);

                    b.Property<DateTime?>("ConfirmationDate");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("EmployeeComment")
                        .HasMaxLength(5000);

                    b.Property<DateTime?>("EmployeeCommentChangeDate");

                    b.Property<DateTime>("EmployeeDate");

                    b.Property<int>("EmployeeId");

                    b.Property<string>("ExternalId")
                        .IsRequired();

                    b.Property<string>("GmComment")
                        .HasMaxLength(5000);

                    b.Property<DateTime?>("GmCommentChangeDate");

                    b.Property<int?>("GmManagerId");

                    b.Property<string>("HrManagerComment")
                        .HasMaxLength(5000);

                    b.Property<DateTime?>("HrManagerCommentChangeDate");

                    b.Property<int?>("HrManagerId");

                    b.Property<DateTime?>("InductionStatusChangeDate");

                    b.Property<string>("InductionStatusChangedBy")
                        .HasMaxLength(64);

                    b.Property<bool>("IsApproved");

                    b.Property<bool>("IsConfirmed");

                    b.Property<bool>("IsEmploymentConfirmedByEmployee");

                    b.Property<bool>("IsInductionPassed");

                    b.Property<int>("LocationId");

                    b.Property<int?>("RelocationCaseStatusId");

                    b.Property<string>("RelocationUnitId")
                        .HasMaxLength(64);

                    b.Property<string>("Salary")
                        .HasMaxLength(1000);

                    b.Property<string>("SourceId");

                    b.Property<string>("State")
                        .IsRequired();

                    b.Property<DateTime?>("StatusDueDate");

                    b.Property<int>("StatusId");

                    b.Property<DateTime>("StatusStartDate");

                    b.Property<DateTime?>("UpdateDate");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.HasIndex("ApproverId");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("GmManagerId");

                    b.HasIndex("HrManagerId");

                    b.HasIndex("LocationId");

                    b.HasIndex("RelocationCaseStatusId");

                    b.HasIndex("State");

                    b.HasIndex("StatusId");

                    b.HasIndex("EmployeeId", "State")
                        .IsUnique()
                        .HasFilter("[State] = 'Active'");

                    b.ToTable("RelocationPlan");
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.RelocationPlanChange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EmployeeId");

                    b.Property<int?>("NewCaseStatusId");

                    b.Property<int?>("NewDestinationId");

                    b.Property<bool?>("NewIsApproved");

                    b.Property<bool?>("NewIsConfirmed");

                    b.Property<bool?>("NewIsEmploymentConfirmedByEmployee");

                    b.Property<bool?>("NewIsInductionPassed");

                    b.Property<int?>("NewStatusId");

                    b.Property<int?>("PreviousCaseStatusId");

                    b.Property<int?>("PreviousDestinationId");

                    b.Property<bool?>("PreviousIsApproved");

                    b.Property<bool?>("PreviousIsConfirmed");

                    b.Property<bool?>("PreviousIsEmploymentConfirmedByEmployee");

                    b.Property<bool?>("PreviousIsInductionPassed");

                    b.Property<int?>("PreviousStatusId");

                    b.Property<int>("RelocationPlanId");

                    b.Property<string>("Type")
                        .IsRequired();

                    b.Property<DateTime>("UpdateDate");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("NewCaseStatusId");

                    b.HasIndex("NewDestinationId");

                    b.HasIndex("NewStatusId");

                    b.HasIndex("PreviousCaseStatusId");

                    b.HasIndex("PreviousDestinationId");

                    b.HasIndex("PreviousStatusId");

                    b.HasIndex("RelocationPlanId");

                    b.HasIndex("Type");

                    b.ToTable("RelocationPlanChange");
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.RelocationPlanStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CaseStatusId");

                    b.Property<string>("ExternalId")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("CaseStatusId")
                        .IsUnique()
                        .HasFilter("[CaseStatusId] IS NOT NULL");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("RelocationPlanStatus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExternalId = "induction",
                            Name = "Induction"
                        },
                        new
                        {
                            Id = 2,
                            ExternalId = "employee_confirmation",
                            Name = "Employee Confirmation"
                        },
                        new
                        {
                            Id = 3,
                            ExternalId = "pending_approval",
                            Name = "Pending Approval"
                        },
                        new
                        {
                            Id = 4,
                            ExternalId = "relocation_approved",
                            Name = "Relocation Approved"
                        },
                        new
                        {
                            Id = 5,
                            ExternalId = "in_progress",
                            Name = "In Progress"
                        },
                        new
                        {
                            Id = 6,
                            ExternalId = "visa_docs_preparation",
                            Name = "Visa Docs Preparation"
                        },
                        new
                        {
                            Id = 7,
                            ExternalId = "waiting_for_embassy_appointment",
                            Name = "Waiting for embassy appointment"
                        },
                        new
                        {
                            Id = 8,
                            ExternalId = "embassy_appointment",
                            Name = "Embassy Appointment"
                        },
                        new
                        {
                            Id = 9,
                            ExternalId = "visa_in_progress",
                            Name = "Visa in Progress"
                        },
                        new
                        {
                            Id = 10,
                            ExternalId = "visa_done",
                            Name = "Visa Done"
                        });
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.RelocationPlanStatusTimeLimit", b =>
                {
                    b.Property<int>("StatusId");

                    b.Property<int?>("TimeLimitDays");

                    b.HasKey("StatusId");

                    b.ToTable("RelocationPlanStatusTimeLimit");

                    b.HasData(
                        new
                        {
                            StatusId = 1,
                            TimeLimitDays = 14
                        },
                        new
                        {
                            StatusId = 2
                        },
                        new
                        {
                            StatusId = 3,
                            TimeLimitDays = 14
                        },
                        new
                        {
                            StatusId = 4,
                            TimeLimitDays = 7
                        },
                        new
                        {
                            StatusId = 5,
                            TimeLimitDays = 14
                        },
                        new
                        {
                            StatusId = 6,
                            TimeLimitDays = 14
                        },
                        new
                        {
                            StatusId = 7,
                            TimeLimitDays = 42
                        },
                        new
                        {
                            StatusId = 8,
                            TimeLimitDays = 14
                        },
                        new
                        {
                            StatusId = 9,
                            TimeLimitDays = 14
                        },
                        new
                        {
                            StatusId = 10,
                            TimeLimitDays = 14
                        });
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ExternalId")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Role");
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.RoleConfiguration", b =>
                {
                    b.Property<int>("Id");

                    b.Property<DateTime?>("UpdateDate");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.ToTable("RoleConfiguration");
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.RoleConfigurationEmployee", b =>
                {
                    b.Property<int>("RoleConfigurationId");

                    b.Property<int>("EmployeeId");

                    b.HasKey("RoleConfigurationId", "EmployeeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("RoleConfigurationEmployee");
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.RoleConfigurationTitleRole", b =>
                {
                    b.Property<int>("RoleConfigurationId");

                    b.Property<int>("TitleRoleId");

                    b.HasKey("RoleConfigurationId", "TitleRoleId");

                    b.HasIndex("TitleRoleId");

                    b.ToTable("RoleConfigurationTitleRole");
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.RoleConfigurationUnit", b =>
                {
                    b.Property<int>("RoleConfigurationId");

                    b.Property<string>("UnitId")
                        .HasMaxLength(64);

                    b.HasKey("RoleConfigurationId", "UnitId");

                    b.ToTable("RoleConfigurationUnit");
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.Seniority", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ExternalId")
                        .IsRequired();

                    b.Property<bool>("IsHidden");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<int>("Order");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("Seniority");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExternalId = "junior",
                            IsHidden = false,
                            Name = "Junior",
                            Order = 1
                        },
                        new
                        {
                            Id = 2,
                            ExternalId = "middle",
                            IsHidden = true,
                            Name = "Middle",
                            Order = 2
                        },
                        new
                        {
                            Id = 3,
                            ExternalId = "senior",
                            IsHidden = false,
                            Name = "Senior",
                            Order = 3
                        },
                        new
                        {
                            Id = 4,
                            ExternalId = "lead",
                            IsHidden = false,
                            Name = "Lead",
                            Order = 4
                        });
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.SyncLog", b =>
                {
                    b.Property<int>("SyncLogId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AffectedInternshipsCount");

                    b.Property<bool>("IsOutdated");

                    b.Property<bool>("IsSuccessful");

                    b.Property<DateTime>("SyncCompletedDate");

                    b.Property<DateTime>("SyncStartDate");

                    b.HasKey("SyncLogId");

                    b.ToTable("SyncLog");
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.TitleRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ExternalId")
                        .IsRequired();

                    b.Property<bool>("HasSeniority");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TitleRole");
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.Repositories.EmployeeServiceDbContext+DismissalReasons", b =>
                {
                    b.Property<string>("Id");

                    b.HasKey("Id");

                    b.ToTable("DismissalReason");

                    b.HasData(
                        new
                        {
                            Id = "Dismissed"
                        },
                        new
                        {
                            Id = "MaternityLeave"
                        });
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.Repositories.EmployeeServiceDbContext+InternshipCloseReasons", b =>
                {
                    b.Property<string>("Id");

                    b.HasKey("Id");

                    b.ToTable("InternshipCloseReason");

                    b.HasData(
                        new
                        {
                            Id = "Manually"
                        },
                        new
                        {
                            Id = "AutomaticallyDueInactivity"
                        },
                        new
                        {
                            Id = "AutomaticallyDueEmployment"
                        });
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.Repositories.EmployeeServiceDbContext+RelocationPlanChangeTypes", b =>
                {
                    b.Property<string>("Id");

                    b.HasKey("Id");

                    b.ToTable("RelocationPlanChangeType");

                    b.HasData(
                        new
                        {
                            Id = "InductionPassed"
                        },
                        new
                        {
                            Id = "Status"
                        },
                        new
                        {
                            Id = "Destination"
                        },
                        new
                        {
                            Id = "Approved"
                        },
                        new
                        {
                            Id = "Confirmed"
                        },
                        new
                        {
                            Id = "EmploymentConfirmedByEmployee"
                        });
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.Repositories.EmployeeServiceDbContext+RelocationPlanStates", b =>
                {
                    b.Property<string>("Id");

                    b.HasKey("Id");

                    b.ToTable("RelocationPlanState");

                    b.HasData(
                        new
                        {
                            Id = "Active"
                        },
                        new
                        {
                            Id = "Completed"
                        },
                        new
                        {
                            Id = "Cancelled"
                        },
                        new
                        {
                            Id = "Rejected"
                        });
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.CompensationInfo", b =>
                {
                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.RelocationPlan", "RelocationPlan")
                        .WithOne("Compensation")
                        .HasForeignKey("DreamTeam.Wod.EmployeeService.DomainModel.CompensationInfo", "RelocationPlanId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.Employee", b =>
                {
                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.EmployeeCurrentLocation", "CurrentLocation")
                        .WithMany()
                        .HasForeignKey("CurrentLocationId");

                    b.HasOne("DreamTeam.Wod.EmployeeService.Repositories.EmployeeServiceDbContext+DismissalReasons")
                        .WithMany()
                        .HasForeignKey("DismissalReason")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.Employee", "ResponsibleHrManager")
                        .WithMany()
                        .HasForeignKey("ResponsibleHrManagerId");

                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.Seniority", "Seniority")
                        .WithMany()
                        .HasForeignKey("SeniorityId");

                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.TitleRole", "TitleRole")
                        .WithMany()
                        .HasForeignKey("TitleRoleId");
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.EmployeeCurrentLocation", b =>
                {
                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.Employee", "Employee")
                        .WithOne()
                        .HasForeignKey("DreamTeam.Wod.EmployeeService.DomainModel.EmployeeCurrentLocation", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.CurrentLocation", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.EmployeeCurrentLocationChange", b =>
                {
                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.CurrentLocation", "NewLocation")
                        .WithMany()
                        .HasForeignKey("NewLocationId");

                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.CurrentLocation", "PreviousLocation")
                        .WithMany()
                        .HasForeignKey("PreviousLocationId");
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.EmployeeOrganizationChange", b =>
                {
                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.EmployeePreferredDeliveryCenter", b =>
                {
                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.EmployeePreferredDeliveryCenters", "EmployeePreferredDeliveryCenters")
                        .WithMany("PreferredDeliveryCenters")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.PreferredDeliveryCenter", "PreferredDeliveryCenter")
                        .WithMany()
                        .HasForeignKey("PreferredDeliveryCenterId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.EmployeePreferredDeliveryCenters", b =>
                {
                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.Employee", "Employee")
                        .WithOne()
                        .HasForeignKey("DreamTeam.Wod.EmployeeService.DomainModel.EmployeePreferredDeliveryCenters", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.EmployeeRole", b =>
                {
                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.Employee", "Employee")
                        .WithMany("Roles")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.Role", "Role")
                        .WithMany("Employees")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.EmployeeSnapshot", b =>
                {
                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.TitleRole", "TitleRole")
                        .WithMany()
                        .HasForeignKey("TitleRoleId");
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.Internship", b =>
                {
                    b.HasOne("DreamTeam.Wod.EmployeeService.Repositories.EmployeeServiceDbContext+InternshipCloseReasons")
                        .WithMany()
                        .HasForeignKey("CloseReason")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.RelocationApprover", b =>
                {
                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.RelocationCaseProgress", b =>
                {
                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.RelocationPlan", "RelocationPlan")
                        .WithOne("RelocationCaseProgress")
                        .HasForeignKey("DreamTeam.Wod.EmployeeService.DomainModel.RelocationCaseProgress", "RelocationPlanId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.RelocationCaseVisaProgress", b =>
                {
                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.RelocationCaseProgress", "RelocationCaseProgress")
                        .WithOne("VisaProgress")
                        .HasForeignKey("DreamTeam.Wod.EmployeeService.DomainModel.RelocationCaseVisaProgress", "RelocationCaseProgressId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.RelocationPlan", b =>
                {
                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.Employee", "Approver")
                        .WithMany()
                        .HasForeignKey("ApproverId");

                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.Employee", "GmManager")
                        .WithMany()
                        .HasForeignKey("GmManagerId");

                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.Employee", "HrManager")
                        .WithMany()
                        .HasForeignKey("HrManagerId");

                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.CurrentLocation", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.RelocationCaseStatus", "RelocationCaseStatus")
                        .WithMany()
                        .HasForeignKey("RelocationCaseStatusId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DreamTeam.Wod.EmployeeService.Repositories.EmployeeServiceDbContext+RelocationPlanStates")
                        .WithMany()
                        .HasForeignKey("State")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.RelocationPlanStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.RelocationPlanChange", b =>
                {
                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.RelocationCaseStatus", "NewCaseStatus")
                        .WithMany()
                        .HasForeignKey("NewCaseStatusId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.CurrentLocation", "NewDestination")
                        .WithMany()
                        .HasForeignKey("NewDestinationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.RelocationPlanStatus", "NewStatus")
                        .WithMany()
                        .HasForeignKey("NewStatusId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.RelocationCaseStatus", "PreviousCaseStatus")
                        .WithMany()
                        .HasForeignKey("PreviousCaseStatusId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.CurrentLocation", "PreviousDestination")
                        .WithMany()
                        .HasForeignKey("PreviousDestinationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.RelocationPlanStatus", "PreviousStatus")
                        .WithMany()
                        .HasForeignKey("PreviousStatusId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.RelocationPlan", "RelocationPlan")
                        .WithMany()
                        .HasForeignKey("RelocationPlanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DreamTeam.Wod.EmployeeService.Repositories.EmployeeServiceDbContext+RelocationPlanChangeTypes")
                        .WithMany()
                        .HasForeignKey("Type")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.RelocationPlanStatus", b =>
                {
                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.RelocationCaseStatus", "CaseStatus")
                        .WithMany()
                        .HasForeignKey("CaseStatusId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.RelocationPlanStatusTimeLimit", b =>
                {
                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.RelocationPlanStatus", "Status")
                        .WithOne()
                        .HasForeignKey("DreamTeam.Wod.EmployeeService.DomainModel.RelocationPlanStatusTimeLimit", "StatusId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.RoleConfiguration", b =>
                {
                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.Role", "Role")
                        .WithOne()
                        .HasForeignKey("DreamTeam.Wod.EmployeeService.DomainModel.RoleConfiguration", "Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.RoleConfigurationEmployee", b =>
                {
                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.RoleConfiguration", "RoleConfiguration")
                        .WithMany("Employees")
                        .HasForeignKey("RoleConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.RoleConfigurationTitleRole", b =>
                {
                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.RoleConfiguration", "RoleConfiguration")
                        .WithMany("TitleRoles")
                        .HasForeignKey("RoleConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.TitleRole", "TitleRole")
                        .WithMany()
                        .HasForeignKey("TitleRoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.RoleConfigurationUnit", b =>
                {
                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.RoleConfiguration", "RoleConfiguration")
                        .WithMany("Units")
                        .HasForeignKey("RoleConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
