// <auto-generated />
using System;
using DreamTeam.Wod.EmployeeService.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DreamTeam.Wod.EmployeeService.Repositories.Migrations
{
    [DbContext(typeof(EmployeeServiceDbContext))]
    [Migration("20220301170210_AddMoreCurrentLocations")]
    partial class AddMoreCurrentLocations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.CurrentLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64);

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("ExternalId")
                        .IsRequired();

                    b.Property<bool>("IsCustom");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("IsCustom");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CurrentLocation");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalId = "minsk",
                            IsCustom = false,
                            Name = "Minsk"
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalId = "mogilev",
                            IsCustom = false,
                            Name = "Mogilev"
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalId = "vitebsk",
                            IsCustom = false,
                            Name = "Vitebsk"
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalId = "brest",
                            IsCustom = false,
                            Name = "Brest"
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalId = "gomel",
                            IsCustom = false,
                            Name = "Gomel"
                        },
                        new
                        {
                            Id = 6,
                            CreationDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalId = "grodno",
                            IsCustom = false,
                            Name = "Grodno"
                        },
                        new
                        {
                            Id = 7,
                            CreationDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalId = "polotsk",
                            IsCustom = false,
                            Name = "Polotsk"
                        },
                        new
                        {
                            Id = 8,
                            CreationDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalId = "new york",
                            IsCustom = false,
                            Name = "New York"
                        },
                        new
                        {
                            Id = 9,
                            CreationDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalId = "san francisco",
                            IsCustom = false,
                            Name = "San Francisco"
                        },
                        new
                        {
                            Id = 10,
                            CreationDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalId = "marietta",
                            IsCustom = false,
                            Name = "Marietta"
                        },
                        new
                        {
                            Id = 11,
                            CreationDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalId = "iselin",
                            IsCustom = false,
                            Name = "Iselin"
                        },
                        new
                        {
                            Id = 12,
                            CreationDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalId = "london",
                            IsCustom = false,
                            Name = "London"
                        },
                        new
                        {
                            Id = 13,
                            CreationDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalId = "lodz",
                            IsCustom = false,
                            Name = "Lodz"
                        },
                        new
                        {
                            Id = 14,
                            CreationDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalId = "vienna",
                            IsCustom = false,
                            Name = "Vienna"
                        },
                        new
                        {
                            Id = 15,
                            CreationDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalId = "kiev",
                            IsCustom = false,
                            Name = "Kiev"
                        },
                        new
                        {
                            Id = 16,
                            CreationDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalId = "lviv",
                            IsCustom = false,
                            Name = "Lviv"
                        },
                        new
                        {
                            Id = 17,
                            CreationDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalId = "wroclaw",
                            IsCustom = false,
                            Name = "Wroclaw"
                        },
                        new
                        {
                            Id = 18,
                            CreationDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalId = "warsaw",
                            IsCustom = false,
                            Name = "Warsaw"
                        },
                        new
                        {
                            Id = 19,
                            CreationDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalId = "tashkent",
                            IsCustom = false,
                            Name = "Tashkent"
                        },
                        new
                        {
                            Id = 20,
                            CreationDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalId = "vilnius",
                            IsCustom = false,
                            Name = "Vilnius"
                        },
                        new
                        {
                            Id = 21,
                            CreationDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalId = "krakow",
                            IsCustom = false,
                            Name = "Krakow"
                        },
                        new
                        {
                            Id = 22,
                            CreationDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalId = "gdansk",
                            IsCustom = false,
                            Name = "Gdansk"
                        },
                        new
                        {
                            Id = 23,
                            CreationDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalId = "tbilisi",
                            IsCustom = false,
                            Name = "Tbilisi"
                        },
                        new
                        {
                            Id = 24,
                            CreationDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalId = "batumi",
                            IsCustom = false,
                            Name = "Batumi"
                        },
                        new
                        {
                            Id = 25,
                            CreationDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalId = "nur-sultan",
                            IsCustom = false,
                            Name = "Nur-Sultan"
                        });
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CountryId")
                        .HasMaxLength(64);

                    b.Property<int?>("CurrentLocationId");

                    b.Property<DateTime?>("DismissalDate");

                    b.Property<string>("DomainName")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<DateTime?>("EmploymentDate");

                    b.Property<string>("ExternalId")
                        .IsRequired();

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsContractor");

                    b.Property<string>("Location");

                    b.Property<DateTime?>("NextPrDate");

                    b.Property<string>("OrganizationId")
                        .HasMaxLength(64);

                    b.Property<string>("PersonId")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<int?>("ResponsibleHrManagerId");

                    b.Property<int?>("SeniorityId");

                    b.Property<string>("UnitId")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<DateTime?>("UpdateDate");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.HasIndex("CurrentLocationId");

                    b.HasIndex("DomainName")
                        .IsUnique();

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.HasIndex("ResponsibleHrManagerId");

                    b.HasIndex("SeniorityId");

                    b.HasIndex("IsActive", "UnitId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.EmployeeCurrentLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ChangeDate");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<int>("EmployeeId");

                    b.Property<int>("LocationId");

                    b.Property<DateTime>("SinceDate");

                    b.Property<DateTime?>("UntilDate");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.HasIndex("LocationId");

                    b.ToTable("EmployeeCurrentLocation");
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.EmployeeRole", b =>
                {
                    b.Property<int>("EmployeeId");

                    b.Property<int>("RoleId");

                    b.HasKey("EmployeeId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("EmployeeRole");
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.Internship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CloseReason");

                    b.Property<string>("CreatedBy")
                        .IsRequired();

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("DomainName")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Email")
                        .HasMaxLength(254);

                    b.Property<DateTime>("EndDate");

                    b.Property<string>("ExternalId")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("FirstNameLocal")
                        .HasMaxLength(200);

                    b.Property<bool>("IsActive");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("LastNameLocal")
                        .HasMaxLength(200);

                    b.Property<string>("Location")
                        .HasMaxLength(100);

                    b.Property<string>("PersonId")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<string>("Phone")
                        .HasMaxLength(64);

                    b.Property<string>("PhotoId")
                        .HasMaxLength(64);

                    b.Property<string>("Skype")
                        .HasMaxLength(256);

                    b.Property<DateTime>("StartDate");

                    b.Property<string>("Telegram")
                        .HasMaxLength(32);

                    b.Property<string>("UnitId")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<DateTime?>("UpdateDate");

                    b.Property<string>("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("CloseReason");

                    b.HasIndex("DomainName");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("Internship");
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(500);

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<bool>("HasSeniority");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Role");
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.Seniority", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ExternalId")
                        .IsRequired();

                    b.Property<bool>("IsHidden");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<int>("Order");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("Seniority");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExternalId = "junior",
                            IsHidden = false,
                            Name = "Junior",
                            Order = 1
                        },
                        new
                        {
                            Id = 2,
                            ExternalId = "middle",
                            IsHidden = true,
                            Name = "Middle",
                            Order = 2
                        },
                        new
                        {
                            Id = 3,
                            ExternalId = "senior",
                            IsHidden = false,
                            Name = "Senior",
                            Order = 3
                        },
                        new
                        {
                            Id = 4,
                            ExternalId = "lead",
                            IsHidden = false,
                            Name = "Lead",
                            Order = 4
                        });
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.Repositories.EmployeeServiceDbContext+InternshipCloseReasons", b =>
                {
                    b.Property<string>("Id");

                    b.HasKey("Id");

                    b.ToTable("InternshipCloseReason");

                    b.HasData(
                        new
                        {
                            Id = "Manually"
                        },
                        new
                        {
                            Id = "AutomaticallyDueInactivity"
                        },
                        new
                        {
                            Id = "AutomaticallyDueEmployment"
                        });
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.Employee", b =>
                {
                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.EmployeeCurrentLocation", "CurrentLocation")
                        .WithMany()
                        .HasForeignKey("CurrentLocationId");

                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.Employee", "ResponsibleHrManager")
                        .WithMany()
                        .HasForeignKey("ResponsibleHrManagerId");

                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.Seniority", "Seniority")
                        .WithMany()
                        .HasForeignKey("SeniorityId");
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.EmployeeCurrentLocation", b =>
                {
                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.Employee", "Employee")
                        .WithOne()
                        .HasForeignKey("DreamTeam.Wod.EmployeeService.DomainModel.EmployeeCurrentLocation", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.CurrentLocation", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.EmployeeRole", b =>
                {
                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.Employee", "Employee")
                        .WithMany("Roles")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.Role", "Role")
                        .WithMany("Employees")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.Internship", b =>
                {
                    b.HasOne("DreamTeam.Wod.EmployeeService.Repositories.EmployeeServiceDbContext+InternshipCloseReasons")
                        .WithMany()
                        .HasForeignKey("CloseReason")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
