// <auto-generated />
using System;
using DreamTeam.Wod.EmployeeService.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DreamTeam.Wod.EmployeeService.Repositories.Migrations
{
    [DbContext(typeof(EmployeeServiceDbContext))]
    [Migration("20220413115655_AddTitleRoles")]
    partial class AddTitleRoles
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.CurrentCountry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ExternalId")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<bool>("SupportsRelocation")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CurrentCountry");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExternalId = "uk",
                            Name = "UK",
                            SupportsRelocation = false
                        },
                        new
                        {
                            Id = 2,
                            ExternalId = "us",
                            Name = "US",
                            SupportsRelocation = false
                        },
                        new
                        {
                            Id = 3,
                            ExternalId = "austria",
                            Name = "Austria",
                            SupportsRelocation = false
                        },
                        new
                        {
                            Id = 4,
                            ExternalId = "belarus",
                            Name = "Belarus",
                            SupportsRelocation = true
                        },
                        new
                        {
                            Id = 5,
                            ExternalId = "georgia",
                            Name = "Georgia",
                            SupportsRelocation = true
                        },
                        new
                        {
                            Id = 6,
                            ExternalId = "kazakhstan",
                            Name = "Kazakhstan",
                            SupportsRelocation = false
                        },
                        new
                        {
                            Id = 7,
                            ExternalId = "lithuania",
                            Name = "Lithuania",
                            SupportsRelocation = true
                        },
                        new
                        {
                            Id = 8,
                            ExternalId = "poland",
                            Name = "Poland",
                            SupportsRelocation = true
                        },
                        new
                        {
                            Id = 9,
                            ExternalId = "ukraine",
                            Name = "Ukraine",
                            SupportsRelocation = true
                        },
                        new
                        {
                            Id = 10,
                            ExternalId = "uzbekistan",
                            Name = "Uzbekistan",
                            SupportsRelocation = true
                        });
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.CurrentLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CountryId");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64);

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("ExternalId")
                        .IsRequired();

                    b.Property<bool>("IsCustom");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("IsCustom");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CurrentLocation");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 4,
                            CreationDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalId = "minsk",
                            IsCustom = false,
                            Name = "Minsk"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 4,
                            CreationDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalId = "mogilev",
                            IsCustom = false,
                            Name = "Mogilev"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 4,
                            CreationDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalId = "vitebsk",
                            IsCustom = false,
                            Name = "Vitebsk"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 4,
                            CreationDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalId = "brest",
                            IsCustom = false,
                            Name = "Brest"
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 4,
                            CreationDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalId = "gomel",
                            IsCustom = false,
                            Name = "Gomel"
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 4,
                            CreationDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalId = "grodno",
                            IsCustom = false,
                            Name = "Grodno"
                        },
                        new
                        {
                            Id = 7,
                            CountryId = 4,
                            CreationDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalId = "polotsk",
                            IsCustom = false,
                            Name = "Polotsk"
                        },
                        new
                        {
                            Id = 8,
                            CountryId = 2,
                            CreationDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalId = "new york",
                            IsCustom = false,
                            Name = "New York"
                        },
                        new
                        {
                            Id = 9,
                            CountryId = 2,
                            CreationDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalId = "san francisco",
                            IsCustom = false,
                            Name = "San Francisco"
                        },
                        new
                        {
                            Id = 10,
                            CountryId = 2,
                            CreationDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalId = "marietta",
                            IsCustom = false,
                            Name = "Marietta"
                        },
                        new
                        {
                            Id = 11,
                            CountryId = 2,
                            CreationDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalId = "iselin",
                            IsCustom = false,
                            Name = "Iselin"
                        },
                        new
                        {
                            Id = 12,
                            CountryId = 1,
                            CreationDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalId = "london",
                            IsCustom = false,
                            Name = "London"
                        },
                        new
                        {
                            Id = 13,
                            CountryId = 8,
                            CreationDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalId = "lodz",
                            IsCustom = false,
                            Name = "Lodz"
                        },
                        new
                        {
                            Id = 14,
                            CountryId = 3,
                            CreationDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalId = "vienna",
                            IsCustom = false,
                            Name = "Vienna"
                        },
                        new
                        {
                            Id = 15,
                            CountryId = 9,
                            CreationDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalId = "kiev",
                            IsCustom = false,
                            Name = "Kiev"
                        },
                        new
                        {
                            Id = 16,
                            CountryId = 9,
                            CreationDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalId = "lviv",
                            IsCustom = false,
                            Name = "Lviv"
                        },
                        new
                        {
                            Id = 17,
                            CountryId = 8,
                            CreationDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalId = "wroclaw",
                            IsCustom = false,
                            Name = "Wroclaw"
                        },
                        new
                        {
                            Id = 18,
                            CountryId = 8,
                            CreationDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalId = "warsaw",
                            IsCustom = false,
                            Name = "Warsaw"
                        },
                        new
                        {
                            Id = 19,
                            CountryId = 10,
                            CreationDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalId = "tashkent",
                            IsCustom = false,
                            Name = "Tashkent"
                        },
                        new
                        {
                            Id = 20,
                            CountryId = 7,
                            CreationDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalId = "vilnius",
                            IsCustom = false,
                            Name = "Vilnius"
                        },
                        new
                        {
                            Id = 21,
                            CountryId = 8,
                            CreationDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalId = "krakow",
                            IsCustom = false,
                            Name = "Krakow"
                        },
                        new
                        {
                            Id = 22,
                            CountryId = 8,
                            CreationDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalId = "gdansk",
                            IsCustom = false,
                            Name = "Gdansk"
                        },
                        new
                        {
                            Id = 23,
                            CountryId = 5,
                            CreationDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalId = "tbilisi",
                            IsCustom = false,
                            Name = "Tbilisi"
                        },
                        new
                        {
                            Id = 24,
                            CountryId = 5,
                            CreationDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalId = "batumi",
                            IsCustom = false,
                            Name = "Batumi"
                        },
                        new
                        {
                            Id = 25,
                            CountryId = 6,
                            CreationDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalId = "nur-sultan",
                            IsCustom = false,
                            Name = "Nur-Sultan"
                        });
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CountryId")
                        .HasMaxLength(64);

                    b.Property<int?>("CurrentLocationId");

                    b.Property<DateTime?>("DismissalDate");

                    b.Property<string>("DomainName")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<DateTime?>("EmploymentDate");

                    b.Property<string>("ExternalId")
                        .IsRequired();

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsContractor");

                    b.Property<string>("Location");

                    b.Property<DateTime?>("NextPrDate");

                    b.Property<string>("OrganizationId")
                        .HasMaxLength(64);

                    b.Property<string>("PersonId")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<int?>("ResponsibleHrManagerId");

                    b.Property<int?>("SeniorityId");

                    b.Property<int?>("TitleRoleId");

                    b.Property<string>("UnitId")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<DateTime?>("UpdateDate");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.HasIndex("CurrentLocationId");

                    b.HasIndex("DomainName")
                        .IsUnique();

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.HasIndex("ResponsibleHrManagerId");

                    b.HasIndex("SeniorityId");

                    b.HasIndex("TitleRoleId");

                    b.HasIndex("IsActive", "UnitId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.EmployeeCurrentLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ChangeDate");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<int>("EmployeeId");

                    b.Property<int>("LocationId");

                    b.Property<DateTime>("SinceDate");

                    b.Property<DateTime?>("UntilDate");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.HasIndex("LocationId");

                    b.ToTable("EmployeeCurrentLocation");
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.EmployeePreferredDeliveryCenter", b =>
                {
                    b.Property<int>("PreferredDeliveryCenterId");

                    b.Property<int>("EmployeeId");

                    b.HasKey("PreferredDeliveryCenterId", "EmployeeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeePreferredDeliveryCenter");
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.EmployeePreferredDeliveryCenters", b =>
                {
                    b.Property<int>("EmployeeId");

                    b.Property<DateTime?>("ChangeDate");

                    b.Property<string>("ChangedBy")
                        .HasMaxLength(64);

                    b.Property<string>("Comment")
                        .HasMaxLength(5000);

                    b.HasKey("EmployeeId");

                    b.ToTable("EmployeePreferredDeliveryCenters");
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.EmployeeRole", b =>
                {
                    b.Property<int>("EmployeeId");

                    b.Property<int>("RoleId");

                    b.HasKey("EmployeeId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("EmployeeRole");
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.Internship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CloseReason");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("DomainName")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Email")
                        .HasMaxLength(254);

                    b.Property<DateTime>("EndDate");

                    b.Property<string>("ExternalId")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("FirstNameLocal")
                        .HasMaxLength(200);

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsDomainNameVerified");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("LastNameLocal")
                        .HasMaxLength(200);

                    b.Property<string>("Location")
                        .HasMaxLength(100);

                    b.Property<string>("PersonId")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<string>("Phone")
                        .HasMaxLength(64);

                    b.Property<string>("PhotoId")
                        .HasMaxLength(64);

                    b.Property<string>("Skype")
                        .HasMaxLength(256);

                    b.Property<DateTime>("StartDate");

                    b.Property<string>("StudentLabId")
                        .HasMaxLength(64);

                    b.Property<string>("StudentLabProfileUrl");

                    b.Property<string>("Telegram")
                        .HasMaxLength(32);

                    b.Property<string>("UnitId")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<DateTime?>("UpdateDate");

                    b.Property<string>("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("CloseReason");

                    b.HasIndex("DomainName");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("Internship");
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.PreferredDeliveryCenter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ExternalId")
                        .IsRequired();

                    b.Property<bool>("IsActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("OrganizationId")
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PreferredDeliveryCenter");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExternalId = "central_asia_kazakhstan_uzbekistan_kyrgyzstan",
                            IsActive = true,
                            Name = "Central Asia (Kazakhstan, Uzbekistan, Kyrgyzstan)"
                        },
                        new
                        {
                            Id = 2,
                            ExternalId = "georgia",
                            IsActive = true,
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = 3,
                            ExternalId = "poland",
                            IsActive = true,
                            Name = "Poland"
                        },
                        new
                        {
                            Id = 4,
                            ExternalId = "lithuania",
                            IsActive = true,
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = 5,
                            ExternalId = "czech_republic_slovakia_hungary",
                            IsActive = true,
                            Name = "Czech Republic, Slovakia, Hungary"
                        },
                        new
                        {
                            Id = 6,
                            ExternalId = "bulgaria_serbia",
                            IsActive = true,
                            Name = "Bulgaria, Serbia"
                        },
                        new
                        {
                            Id = 7,
                            ExternalId = "latam",
                            IsActive = true,
                            Name = "LATAM"
                        },
                        new
                        {
                            Id = 8,
                            ExternalId = "belarus",
                            IsActive = false,
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = 9,
                            ExternalId = "ukraine",
                            IsActive = false,
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = 10,
                            ExternalId = "uk",
                            IsActive = false,
                            Name = "UK"
                        },
                        new
                        {
                            Id = 11,
                            ExternalId = "us",
                            IsActive = false,
                            Name = "US"
                        },
                        new
                        {
                            Id = 12,
                            ExternalId = "austria",
                            IsActive = false,
                            Name = "Austria"
                        });
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.RelocationPlan", b =>
                {
                    b.Property<int>("EmployeeId");

                    b.Property<string>("Comment")
                        .HasMaxLength(5000);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<DateTime>("CreationDate");

                    b.Property<DateTime>("Date");

                    b.Property<string>("GmVisaState");

                    b.Property<DateTime?>("GmVisaStateChangeDate");

                    b.Property<string>("GmVisaStateChangedBy")
                        .HasMaxLength(64);

                    b.Property<int>("LocationId");

                    b.Property<DateTime?>("UpdateDate");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(64);

                    b.Property<string>("VisaState")
                        .IsRequired();

                    b.Property<bool>("WithEmployment");

                    b.HasKey("EmployeeId");

                    b.HasIndex("GmVisaState");

                    b.HasIndex("LocationId");

                    b.HasIndex("VisaState");

                    b.ToTable("RelocationPlan");
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ExternalId")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Role");
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.Seniority", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ExternalId")
                        .IsRequired();

                    b.Property<bool>("IsHidden");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<int>("Order");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("Seniority");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExternalId = "junior",
                            IsHidden = false,
                            Name = "Junior",
                            Order = 1
                        },
                        new
                        {
                            Id = 2,
                            ExternalId = "middle",
                            IsHidden = true,
                            Name = "Middle",
                            Order = 2
                        },
                        new
                        {
                            Id = 3,
                            ExternalId = "senior",
                            IsHidden = false,
                            Name = "Senior",
                            Order = 3
                        },
                        new
                        {
                            Id = 4,
                            ExternalId = "lead",
                            IsHidden = false,
                            Name = "Lead",
                            Order = 4
                        });
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.SyncLog", b =>
                {
                    b.Property<int>("SyncLogId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AffectedInternshipsCount");

                    b.Property<bool>("IsOutdated");

                    b.Property<bool>("IsSuccessful");

                    b.Property<DateTime>("SyncCompletedDate");

                    b.Property<DateTime>("SyncStartDate");

                    b.HasKey("SyncLogId");

                    b.ToTable("SyncLog");
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.TitleRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ExternalId")
                        .IsRequired();

                    b.Property<bool>("HasSeniority");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TitleRole");
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.Repositories.EmployeeServiceDbContext+GmVisaStates", b =>
                {
                    b.Property<string>("Id");

                    b.HasKey("Id");

                    b.ToTable("GmVisaState");

                    b.HasData(
                        new
                        {
                            Id = "RequireVerification"
                        },
                        new
                        {
                            Id = "Pending"
                        },
                        new
                        {
                            Id = "Agency"
                        },
                        new
                        {
                            Id = "EmbassyAppointment"
                        },
                        new
                        {
                            Id = "VisaInProgress"
                        },
                        new
                        {
                            Id = "VisaDone"
                        },
                        new
                        {
                            Id = "VisaNotValid"
                        });
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.Repositories.EmployeeServiceDbContext+InternshipCloseReasons", b =>
                {
                    b.Property<string>("Id");

                    b.HasKey("Id");

                    b.ToTable("InternshipCloseReason");

                    b.HasData(
                        new
                        {
                            Id = "Manually"
                        },
                        new
                        {
                            Id = "AutomaticallyDueInactivity"
                        },
                        new
                        {
                            Id = "AutomaticallyDueEmployment"
                        });
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.Repositories.EmployeeServiceDbContext+VisaStates", b =>
                {
                    b.Property<string>("Id");

                    b.HasKey("Id");

                    b.ToTable("VisaState");

                    b.HasData(
                        new
                        {
                            Id = "Acquired"
                        },
                        new
                        {
                            Id = "InProgress"
                        },
                        new
                        {
                            Id = "NotRequired"
                        },
                        new
                        {
                            Id = "RequireAssistance"
                        });
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.CurrentLocation", b =>
                {
                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.CurrentCountry", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId");
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.Employee", b =>
                {
                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.EmployeeCurrentLocation", "CurrentLocation")
                        .WithMany()
                        .HasForeignKey("CurrentLocationId");

                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.Employee", "ResponsibleHrManager")
                        .WithMany()
                        .HasForeignKey("ResponsibleHrManagerId");

                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.Seniority", "Seniority")
                        .WithMany()
                        .HasForeignKey("SeniorityId");

                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.TitleRole", "TitleRole")
                        .WithMany()
                        .HasForeignKey("TitleRoleId");
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.EmployeeCurrentLocation", b =>
                {
                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.Employee", "Employee")
                        .WithOne()
                        .HasForeignKey("DreamTeam.Wod.EmployeeService.DomainModel.EmployeeCurrentLocation", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.CurrentLocation", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.EmployeePreferredDeliveryCenter", b =>
                {
                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.EmployeePreferredDeliveryCenters", "EmployeePreferredDeliveryCenters")
                        .WithMany("PreferredDeliveryCenters")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.PreferredDeliveryCenter", "PreferredDeliveryCenter")
                        .WithMany()
                        .HasForeignKey("PreferredDeliveryCenterId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.EmployeePreferredDeliveryCenters", b =>
                {
                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.Employee", "Employee")
                        .WithOne()
                        .HasForeignKey("DreamTeam.Wod.EmployeeService.DomainModel.EmployeePreferredDeliveryCenters", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.EmployeeRole", b =>
                {
                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.Employee", "Employee")
                        .WithMany("Roles")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.Role", "Role")
                        .WithMany("Employees")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.Internship", b =>
                {
                    b.HasOne("DreamTeam.Wod.EmployeeService.Repositories.EmployeeServiceDbContext+InternshipCloseReasons")
                        .WithMany()
                        .HasForeignKey("CloseReason")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("DreamTeam.Wod.EmployeeService.DomainModel.RelocationPlan", b =>
                {
                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.Employee", "Employee")
                        .WithOne()
                        .HasForeignKey("DreamTeam.Wod.EmployeeService.DomainModel.RelocationPlan", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DreamTeam.Wod.EmployeeService.Repositories.EmployeeServiceDbContext+GmVisaStates")
                        .WithMany()
                        .HasForeignKey("GmVisaState")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DreamTeam.Wod.EmployeeService.DomainModel.CurrentLocation", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DreamTeam.Wod.EmployeeService.Repositories.EmployeeServiceDbContext+VisaStates")
                        .WithMany()
                        .HasForeignKey("VisaState")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
